// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npthsbvqsovzbajfnnel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdGhzYnZxc292emJhamZubmVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODQ2NDksImV4cCI6MjA2MzY2MDY0OX0.HHGlIZ5MbM-grR5zDZo88IVQgwyXj6CPcZ6LCqmQP1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);